import type { StoreResult, Restaurant, FeedPost, MealPlan } from "./contracts.ts";

export const MOCK_STORES: StoreResult[] = [
  {
    store_id: "s1",
    name: "Пятёрочка",
    distance_m: 280,
    total_price: 1240,
    delivery_min: 30,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3.6,
        carbs: 0,
        weight_g: 500,
        price_rub: 219,
      },
      {
        name: "Греческий йогурт",
        kcal: 66,
        protein: 5,
        fat: 0.4,
        carbs: 9,
        weight_g: 200,
        price_rub: 89,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 69,
      },
    ],
    missing: [],
  },
  {
    store_id: "s2",
    name: "Перекрёсток",
    distance_m: 650,
    total_price: 1410,
    delivery_min: 45,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3.6,
        carbs: 0,
        weight_g: 500,
        price_rub: 239,
      },
      {
        name: "Греческий йогурт",
        kcal: 66,
        protein: 5,
        fat: 0.4,
        carbs: 9,
        weight_g: 200,
        price_rub: 99,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 79,
      },
    ],
    missing: ["Творог 5%"],
  },
  {
    store_id: "s3",
    name: "ВкусВилл",
    distance_m: 920,
    total_price: 1680,
    delivery_min: 55,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3.6,
        carbs: 0,
        weight_g: 500,
        price_rub: 289,
      },
      {
        name: "Греческий йогурт",
        kcal: 66,
        protein: 5,
        fat: 0.4,
        carbs: 9,
        weight_g: 200,
        price_rub: 119,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 89,
      },
    ],
    missing: [],
  },
  {
    store_id: "s4",
    name: "Магнит",
    distance_m: 1100,
    total_price: 1180,
    delivery_min: 60,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3.6,
        carbs: 0,
        weight_g: 500,
        price_rub: 199,
      },
      {
        name: "Греческий йогурт",
        kcal: 66,
        protein: 5,
        fat: 0.4,
        carbs: 9,
        weight_g: 200,
        price_rub: 79,
      },
    ],
    missing: ["Творог 5%", "Овсяные хлопья"],
  },
];

// ─── Restaurants (2GIS mock — ~500m from Kutuzovsky 32k1) ────────────────────

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Теремок",
    address: "Кутузовский пр-т, 24",
    distance_m: 320,
    walk_kcal: 22,
    dishes: [
      {
        name: "Блины с курицей",
        kcal: 380,
        protein: 28,
        fat: 12,
        carbs: 38,
        price_rub: 299,
      },
      {
        name: "Каша гречневая",
        kcal: 210,
        protein: 8,
        fat: 4,
        carbs: 38,
        price_rub: 149,
      },
      {
        name: "Щи со сметаной",
        kcal: 180,
        protein: 9,
        fat: 7,
        carbs: 20,
        price_rub: 189,
      },
    ],
  },
  {
    id: "r2",
    name: "Дodo Пицца",
    address: "Кутузовский пр-т, 36",
    distance_m: 480,
    walk_kcal: 34,
    dishes: [
      {
        name: "Пицца Гавайская (кусок)",
        kcal: 245,
        protein: 14,
        fat: 8,
        carbs: 30,
        price_rub: 189,
      },
      {
        name: "Цезарь с курицей",
        kcal: 320,
        protein: 22,
        fat: 14,
        carbs: 24,
        price_rub: 249,
      },
      {
        name: "Суп дня",
        kcal: 190,
        protein: 11,
        fat: 6,
        carbs: 22,
        price_rub: 169,
      },
    ],
  },
  {
    id: "r3",
    name: "Якитория",
    address: "ТРЦ Европейский, 1 эт.",
    distance_m: 600,
    walk_kcal: 42,
    dishes: [
      {
        name: "Мисо-суп",
        kcal: 72,
        protein: 5,
        fat: 2,
        carbs: 8,
        price_rub: 149,
      },
      {
        name: "Тунец Татаки",
        kcal: 180,
        protein: 24,
        fat: 5,
        carbs: 8,
        price_rub: 389,
      },
      {
        name: "Рис с лососем",
        kcal: 310,
        protein: 18,
        fat: 6,
        carbs: 44,
        price_rub: 299,
      },
    ],
  },
  {
    id: "r4",
    name: "Prime Beef",
    address: "Кутузовский пр-т, 2/1",
    distance_m: 850,
    walk_kcal: 60,
    dishes: [
      {
        name: "Стейк Рибай",
        kcal: 490,
        protein: 42,
        fat: 34,
        carbs: 0,
        price_rub: 1290,
      },
      {
        name: "Греческий салат",
        kcal: 180,
        protein: 6,
        fat: 12,
        carbs: 12,
        price_rub: 390,
      },
      {
        name: "Куриный суп",
        kcal: 140,
        protein: 12,
        fat: 4,
        carbs: 14,
        price_rub: 290,
      },
    ],
  },
];


export const MOCK_FEED: FeedPost[] = [
  {
    id: "p1",
    user_id: "u1",
    user_name: "Алексей М.",
    type: "dish",
    dish_name: "Блины с курицей",
    body: "Отличный обед сегодня — сытно и почти в норму по белку. Теремок снова не подвёл!",
    kcal: 380,
    protein: 28,
    fat: 12,
    carbs: 38,
    place_name: "Теремок",
    distance_m: 320,
    walk_kcal: 22,
    likes_count: 14,
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: "p2",
    user_id: "u2",
    user_name: "Марина К.",
    type: "achievement",
    dish_name: "",
    body: "Марина, 7 дней без срывов — это просто огонь! 🔥 Продолжай в том же духе!",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    likes_count: 31,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];


export const MOCK_MEAL_PLAN: MealPlan = {
  meals: [
    {
      day: 1,
      meal_type: "breakfast",
      dish: "Овсяная каша с ягодами",
      kcal: 320,
      protein: 10,
      fat: 6,
      carbs: 54,
    },
    {
      day: 1,
      meal_type: "lunch",
      dish: "Куриная грудка с гречкой",
      kcal: 480,
      protein: 42,
      fat: 9,
      carbs: 48,
    },
    {
      day: 1,
      meal_type: "snack",
      dish: "Греческий йогурт",
      kcal: 130,
      protein: 10,
      fat: 3,
      carbs: 14,
    },
    {
      day: 1,
      meal_type: "dinner",
      dish: "Лосось на пару с овощами",
      kcal: 390,
      protein: 36,
      fat: 16,
      carbs: 18,
    },
    {
      day: 2,
      meal_type: "breakfast",
      dish: "Яичница с авокадо",
      kcal: 360,
      protein: 18,
      fat: 24,
      carbs: 10,
    },
    {
      day: 2,
      meal_type: "lunch",
      dish: "Суп из чечевицы",
      kcal: 290,
      protein: 16,
      fat: 5,
      carbs: 46,
    },
    {
      day: 2,
      meal_type: "snack",
      dish: "Творог с мёдом",
      kcal: 180,
      protein: 14,
      fat: 4,
      carbs: 20,
    },
    {
      day: 2,
      meal_type: "dinner",
      dish: "Индейка с брокколи",
      kcal: 340,
      protein: 38,
      fat: 8,
      carbs: 22,
    },
    {
      day: 3,
      meal_type: "breakfast",
      dish: "Смузи с бананом и протеином",
      kcal: 280,
      protein: 22,
      fat: 4,
      carbs: 38,
    },
    {
      day: 3,
      meal_type: "lunch",
      dish: "Тунец с рисом",
      kcal: 420,
      protein: 34,
      fat: 6,
      carbs: 54,
    },
    {
      day: 3,
      meal_type: "snack",
      dish: "Миндаль 30г",
      kcal: 175,
      protein: 6,
      fat: 15,
      carbs: 6,
    },
    {
      day: 3,
      meal_type: "dinner",
      dish: "Говядина с запечёнными овощами",
      kcal: 410,
      protein: 36,
      fat: 14,
      carbs: 28,
    },
  ],
  shopping_list: [
    { product: "Куриная грудка", qty: 600, unit: "г" },
    { product: "Греческий йогурт", qty: 400, unit: "г" },
    { product: "Овсяные хлопья", qty: 200, unit: "г" },
    { product: "Творог 5%", qty: 300, unit: "г" },
    { product: "Лосось", qty: 300, unit: "г" },
  ],
};
