import type { StoreResult, Restaurant, FeedPost, MealPlan, MealItem, OrderHistoryItem, CartData } from "./contracts";

// ─── Stores ───────────────────────────────────────────────────────────────────

export const MOCK_STORES: StoreResult[] = [
  {
    store_id: "s1",
    name: "Пятёрочка",
    type: "supermarket",
    distance_m: 280,
    total_price: 1240,
    delivery_min: 30,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3,
        carbs: 0,
        weight_g: 500,
        price_rub: 219,
      },
      {
        name: "Греч. йогурт",
        kcal: 66,
        protein: 5,
        fat: 0,
        carbs: 9,
        weight_g: 200,
        price_rub: 89,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 69,
      },
      {
        name: "Яйца C1",
        kcal: 157,
        protein: 13,
        fat: 11,
        carbs: 1,
        weight_g: 600,
        price_rub: 99,
      },
      {
        name: "Творог 5%",
        kcal: 121,
        protein: 17,
        fat: 5,
        carbs: 3,
        weight_g: 200,
        price_rub: 79,
      },
      {
        name: "Гречка",
        kcal: 313,
        protein: 12,
        fat: 3,
        carbs: 62,
        weight_g: 800,
        price_rub: 89,
      },
      {
        name: "Молоко 2.5%",
        kcal: 52,
        protein: 3,
        fat: 3,
        carbs: 5,
        weight_g: 1000,
        price_rub: 79,
      },
    ],
    missing: [],
  },
  {
    store_id: "s2",
    name: "Перекрёсток",
    type: "supermarket",
    distance_m: 650,
    total_price: 1410,
    delivery_min: 45,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3,
        carbs: 0,
        weight_g: 500,
        price_rub: 239,
      },
      {
        name: "Греч. йогурт",
        kcal: 66,
        protein: 5,
        fat: 0,
        carbs: 9,
        weight_g: 200,
        price_rub: 99,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 79,
      },
      {
        name: "Лосось с/с",
        kcal: 202,
        protein: 20,
        fat: 13,
        carbs: 0,
        weight_g: 300,
        price_rub: 389,
      },
      {
        name: "Брокколи зам.",
        kcal: 34,
        protein: 3,
        fat: 0,
        carbs: 7,
        weight_g: 400,
        price_rub: 99,
      },
      {
        name: "Миндаль",
        kcal: 579,
        protein: 21,
        fat: 50,
        carbs: 22,
        weight_g: 150,
        price_rub: 249,
      },
    ],
    missing: ["Творог 5%"],
  },
  {
    store_id: "s3",
    name: "ВкусВилл",
    type: "supermarket",
    distance_m: 920,
    total_price: 1680,
    delivery_min: 55,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3,
        carbs: 0,
        weight_g: 500,
        price_rub: 289,
      },
      {
        name: "Греч. йогурт",
        kcal: 66,
        protein: 5,
        fat: 0,
        carbs: 9,
        weight_g: 200,
        price_rub: 119,
      },
      {
        name: "Тунец в с/с",
        kcal: 96,
        protein: 22,
        fat: 1,
        carbs: 0,
        weight_g: 185,
        price_rub: 169,
      },
      {
        name: "Творог 0%",
        kcal: 71,
        protein: 16,
        fat: 0,
        carbs: 2,
        weight_g: 200,
        price_rub: 99,
      },
      {
        name: "Авокадо",
        kcal: 160,
        protein: 2,
        fat: 15,
        carbs: 9,
        weight_g: 200,
        price_rub: 149,
      },
      {
        name: "Индейка филе",
        kcal: 157,
        protein: 29,
        fat: 4,
        carbs: 0,
        weight_g: 500,
        price_rub: 319,
      },
      {
        name: "Овсяные хлопья",
        kcal: 367,
        protein: 13,
        fat: 7,
        carbs: 62,
        weight_g: 400,
        price_rub: 89,
      },
    ],
    missing: [],
  },
  {
    store_id: "s4",
    name: "Магнит",
    type: "supermarket",
    distance_m: 1100,
    total_price: 1180,
    delivery_min: 60,
    available: [
      {
        name: "Куриная грудка",
        kcal: 165,
        protein: 31,
        fat: 3,
        carbs: 0,
        weight_g: 500,
        price_rub: 199,
      },
      {
        name: "Греч. йогурт",
        kcal: 66,
        protein: 5,
        fat: 0,
        carbs: 9,
        weight_g: 200,
        price_rub: 79,
      },
      {
        name: "Яйца С0",
        kcal: 157,
        protein: 13,
        fat: 11,
        carbs: 1,
        weight_g: 600,
        price_rub: 109,
      },
      {
        name: "Рис длиннозёрный",
        kcal: 344,
        protein: 7,
        fat: 1,
        carbs: 77,
        weight_g: 800,
        price_rub: 79,
      },
      {
        name: "Кефир 1%",
        kcal: 40,
        protein: 3,
        fat: 1,
        carbs: 5,
        weight_g: 900,
        price_rub: 69,
      },
      {
        name: "Макароны",
        kcal: 352,
        protein: 12,
        fat: 2,
        carbs: 72,
        weight_g: 400,
        price_rub: 59,
      },
    ],
    missing: ["Творог 5%", "Овсяные хлопья"],
  },
  {
    store_id: "s5",
    name: "Яндекс Лавка",
    type: "darkstore",
    distance_m: 0,
    total_price: 1390,
    delivery_min: 15,
    available: [
      { name: "Куриная грудка", kcal: 165, protein: 31, fat: 3, carbs: 0, weight_g: 500, price_rub: 249 },
      { name: "Греч. йогурт", kcal: 66, protein: 5, fat: 0, carbs: 9, weight_g: 200, price_rub: 99 },
      { name: "Овсяные хлопья", kcal: 367, protein: 13, fat: 7, carbs: 62, weight_g: 400, price_rub: 89 },
      { name: "Яйца С1", kcal: 157, protein: 13, fat: 11, carbs: 1, weight_g: 600, price_rub: 119 },
      { name: "Творог 5%", kcal: 121, protein: 17, fat: 5, carbs: 3, weight_g: 200, price_rub: 89 },
      { name: "Банан", kcal: 89, protein: 1, fat: 0, carbs: 23, weight_g: 400, price_rub: 69 },
      { name: "Молоко 2.5%", kcal: 52, protein: 3, fat: 3, carbs: 5, weight_g: 1000, price_rub: 89 },
    ],
    missing: [],
  },
  {
    store_id: "s6",
    name: "Самокат",
    type: "darkstore",
    distance_m: 0,
    total_price: 1320,
    delivery_min: 20,
    available: [
      { name: "Куриная грудка", kcal: 165, protein: 31, fat: 3, carbs: 0, weight_g: 500, price_rub: 229 },
      { name: "Греч. йогурт", kcal: 66, protein: 5, fat: 0, carbs: 9, weight_g: 200, price_rub: 85 },
      { name: "Овсяные хлопья", kcal: 367, protein: 13, fat: 7, carbs: 62, weight_g: 400, price_rub: 75 },
      { name: "Яйца С1", kcal: 157, protein: 13, fat: 11, carbs: 1, weight_g: 600, price_rub: 105 },
      { name: "Гречка", kcal: 313, protein: 12, fat: 3, carbs: 62, weight_g: 800, price_rub: 85 },
      { name: "Кефир 1%", kcal: 40, protein: 3, fat: 1, carbs: 5, weight_g: 900, price_rub: 75 },
    ],
    missing: ["Творог 5%"],
  },
];

// ─── Restaurants ──────────────────────────────────────────────────────────────

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Теремок",
    address: "Кутузовский пр-т, 24",
    distance_m: 320,
    walk_kcal: 22,
    dishes: [
      {
        name: "Блины с курицей",
        kcal: 380,
        protein: 28,
        fat: 12,
        carbs: 38,
        price_rub: 299,
      },
      {
        name: "Каша гречневая",
        kcal: 210,
        protein: 8,
        fat: 4,
        carbs: 38,
        price_rub: 149,
      },
      {
        name: "Щи со сметаной",
        kcal: 180,
        protein: 9,
        fat: 7,
        carbs: 20,
        price_rub: 189,
      },
      {
        name: "Блины с лососем",
        kcal: 420,
        protein: 26,
        fat: 18,
        carbs: 38,
        price_rub: 369,
      },
      {
        name: "Овсяная каша",
        kcal: 190,
        protein: 6,
        fat: 4,
        carbs: 32,
        price_rub: 129,
      },
      {
        name: "Курник",
        kcal: 340,
        protein: 18,
        fat: 14,
        carbs: 36,
        price_rub: 259,
      },
      {
        name: "Борщ",
        kcal: 165,
        protein: 8,
        fat: 6,
        carbs: 22,
        price_rub: 179,
      },
    ],
  },
  {
    id: "r2",
    name: "Dodo Пицца",
    address: "Кутузовский пр-т, 36",
    distance_m: 480,
    walk_kcal: 34,
    dishes: [
      {
        name: "Пицца Гавайская",
        kcal: 245,
        protein: 14,
        fat: 8,
        carbs: 30,
        price_rub: 189,
      },
      {
        name: "Цезарь с курицей",
        kcal: 320,
        protein: 22,
        fat: 14,
        carbs: 24,
        price_rub: 249,
      },
      {
        name: "Суп дня",
        kcal: 190,
        protein: 11,
        fat: 6,
        carbs: 22,
        price_rub: 169,
      },
      {
        name: "Пицца Пепперони",
        kcal: 270,
        protein: 13,
        fat: 11,
        carbs: 31,
        price_rub: 199,
      },
      {
        name: "Додстер с курицей",
        kcal: 310,
        protein: 18,
        fat: 12,
        carbs: 34,
        price_rub: 219,
      },
      {
        name: "Картофель дольками",
        kcal: 220,
        protein: 4,
        fat: 9,
        carbs: 32,
        price_rub: 149,
      },
    ],
  },
  {
    id: "r3",
    name: "Якитория",
    address: "ТРЦ Европейский, 1 эт.",
    distance_m: 600,
    walk_kcal: 42,
    dishes: [
      {
        name: "Мисо-суп",
        kcal: 72,
        protein: 5,
        fat: 2,
        carbs: 8,
        price_rub: 149,
      },
      {
        name: "Тунец Татаки",
        kcal: 180,
        protein: 24,
        fat: 5,
        carbs: 8,
        price_rub: 389,
      },
      {
        name: "Рис с лососем",
        kcal: 310,
        protein: 18,
        fat: 6,
        carbs: 44,
        price_rub: 299,
      },
      {
        name: "Роллы Калифорния",
        kcal: 255,
        protein: 11,
        fat: 7,
        carbs: 36,
        price_rub: 329,
      },
      {
        name: "Эдамаме",
        kcal: 120,
        protein: 11,
        fat: 5,
        carbs: 10,
        price_rub: 199,
      },
      {
        name: "Том Ям",
        kcal: 210,
        protein: 14,
        fat: 9,
        carbs: 18,
        price_rub: 349,
      },
      {
        name: "Гюдон с говядиной",
        kcal: 420,
        protein: 26,
        fat: 14,
        carbs: 48,
        price_rub: 379,
      },
    ],
  },
  {
    id: "r4",
    name: "Prime Beef",
    address: "Кутузовский пр-т, 2/1",
    distance_m: 850,
    walk_kcal: 60,
    dishes: [
      {
        name: "Стейк Рибай 200г",
        kcal: 490,
        protein: 42,
        fat: 34,
        carbs: 0,
        price_rub: 1290,
      },
      {
        name: "Греческий салат",
        kcal: 180,
        protein: 6,
        fat: 12,
        carbs: 12,
        price_rub: 390,
      },
      {
        name: "Куриный суп",
        kcal: 140,
        protein: 12,
        fat: 4,
        carbs: 14,
        price_rub: 290,
      },
      {
        name: "Бёф Бургиньон",
        kcal: 380,
        protein: 28,
        fat: 18,
        carbs: 22,
        price_rub: 590,
      },
      {
        name: "Запечённые овощи",
        kcal: 120,
        protein: 3,
        fat: 5,
        carbs: 18,
        price_rub: 290,
      },
      {
        name: "Тартар из говядины",
        kcal: 220,
        protein: 20,
        fat: 14,
        carbs: 4,
        price_rub: 490,
      },
    ],
  },
];

// ─── Feed ─────────────────────────────────────────────────────────────────────

export const MOCK_FEED: FeedPost[] = [
  {
    id: "p1",
    user_id: "u1",
    user_name: "Алексей М.",
    type: "dish",
    dish_name: "Блины с курицей",
    body: "Отличный обед — сытно и почти в норму по белку. Теремок снова не подвёл!",
    kcal: 380,
    protein: 28,
    fat: 12,
    carbs: 38,
    place_name: "Теремок",
    distance_m: 320,
    walk_kcal: 22,
    likes_count: 14,
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: "p2",
    user_id: "u2",
    user_name: "Марина К.",
    type: "achievement",
    dish_name: "",
    body: "Марина, 7 дней без срывов — это просто огонь! 🔥 Продолжай в том же духе!",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    likes_count: 31,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];

// ─── Meal plan (day 1, ~1320 kcal) ───────────────────────────────────────────

export const MOCK_MEAL_PLAN: MealPlan = {
  meals: [
    {
      day: 1,
      meal_type: "breakfast",
      dish: "Овсяная каша с ягодами",
      kcal: 320,
      protein: 10,
      fat: 6,
      carbs: 54,
    },
    {
      day: 1,
      meal_type: "lunch",
      dish: "Куриная грудка с гречкой",
      kcal: 480,
      protein: 42,
      fat: 9,
      carbs: 48,
    },
    {
      day: 1,
      meal_type: "snack",
      dish: "Греческий йогурт",
      kcal: 130,
      protein: 10,
      fat: 3,
      carbs: 14,
    },
    {
      day: 1,
      meal_type: "dinner",
      dish: "Лосось на пару с овощами",
      kcal: 390,
      protein: 36,
      fat: 16,
      carbs: 18,
    },
  ],
  shopping_list: [
    { product: "Куриная грудка", qty: 600, unit: "г" },
    { product: "Греческий йогурт", qty: 400, unit: "г" },
    { product: "Овсяные хлопья", qty: 200, unit: "г" },
    { product: "Творог 5%", qty: 300, unit: "г" },
    { product: "Лосось", qty: 300, unit: "г" },
    { product: "Брокколи", qty: 200, unit: "г" },
    { product: "Яйца", qty: 4, unit: "шт" },
  ],
};

// ─── Alternative meal plans ─────────────────────────────────────────────────

export const MOCK_MEAL_PLAN_NEW: MealPlan = {
  meals: [
    { day: 1, meal_type: "breakfast", dish: "Смузи-боул с манго и чиа", kcal: 290, protein: 8, fat: 10, carbs: 42 },
    { day: 1, meal_type: "lunch", dish: "Поке с тунцом и эдамаме", kcal: 510, protein: 38, fat: 14, carbs: 52 },
    { day: 1, meal_type: "snack", dish: "Хумус с овощными палочками", kcal: 150, protein: 6, fat: 8, carbs: 14 },
    { day: 1, meal_type: "dinner", dish: "Том Ям с креветками", kcal: 340, protein: 28, fat: 12, carbs: 26 },
  ],
  shopping_list: [
    { product: "Тунец свежий", qty: 200, unit: "г" },
    { product: "Манго", qty: 1, unit: "шт" },
    { product: "Семена чиа", qty: 30, unit: "г" },
    { product: "Креветки", qty: 300, unit: "г" },
    { product: "Хумус", qty: 200, unit: "г" },
    { product: "Эдамаме", qty: 150, unit: "г" },
  ],
};

export const MOCK_MEAL_PLAN_MIX: MealPlan = {
  meals: [
    { day: 1, meal_type: "breakfast", dish: "Сырники со сметаной", kcal: 310, protein: 16, fat: 12, carbs: 34 },
    { day: 1, meal_type: "lunch", dish: "Боул с киноа и авокадо", kcal: 460, protein: 18, fat: 22, carbs: 48 },
    { day: 1, meal_type: "snack", dish: "Творог с мёдом и орехами", kcal: 180, protein: 14, fat: 6, carbs: 18 },
    { day: 1, meal_type: "dinner", dish: "Индейка с запечёнными овощами", kcal: 370, protein: 34, fat: 10, carbs: 28 },
  ],
  shopping_list: [
    { product: "Творог 9%", qty: 400, unit: "г" },
    { product: "Сметана 15%", qty: 100, unit: "г" },
    { product: "Киноа", qty: 150, unit: "г" },
    { product: "Авокадо", qty: 1, unit: "шт" },
    { product: "Индейка филе", qty: 400, unit: "г" },
    { product: "Мёд", qty: 30, unit: "г" },
    { product: "Миндаль", qty: 30, unit: "г" },
  ],
};

// ─── Alternative meals per slot ─────────────────────────────────────────────

export const MOCK_ALTERNATIVES: Record<string, MealItem[]> = {
  breakfast: [
    { day: 1, meal_type: "breakfast", dish: "Овсяная каша с ягодами", kcal: 320, protein: 10, fat: 6, carbs: 54 },
    { day: 1, meal_type: "breakfast", dish: "Сырники со сметаной", kcal: 310, protein: 16, fat: 12, carbs: 34 },
    { day: 1, meal_type: "breakfast", dish: "Смузи-боул с манго и чиа", kcal: 290, protein: 8, fat: 10, carbs: 42 },
    { day: 1, meal_type: "breakfast", dish: "Омлет с овощами и сыром", kcal: 340, protein: 22, fat: 18, carbs: 12 },
    { day: 1, meal_type: "breakfast", dish: "Тосты с авокадо и яйцом", kcal: 360, protein: 14, fat: 20, carbs: 32 },
  ],
  lunch: [
    { day: 1, meal_type: "lunch", dish: "Куриная грудка с гречкой", kcal: 480, protein: 42, fat: 9, carbs: 48 },
    { day: 1, meal_type: "lunch", dish: "Поке с тунцом и эдамаме", kcal: 510, protein: 38, fat: 14, carbs: 52 },
    { day: 1, meal_type: "lunch", dish: "Боул с киноа и авокадо", kcal: 460, protein: 18, fat: 22, carbs: 48 },
    { day: 1, meal_type: "lunch", dish: "Паста с курицей и песто", kcal: 520, protein: 32, fat: 16, carbs: 58 },
    { day: 1, meal_type: "lunch", dish: "Борщ с говядиной", kcal: 420, protein: 28, fat: 12, carbs: 44 },
  ],
  snack: [
    { day: 1, meal_type: "snack", dish: "Греческий йогурт", kcal: 130, protein: 10, fat: 3, carbs: 14 },
    { day: 1, meal_type: "snack", dish: "Хумус с овощными палочками", kcal: 150, protein: 6, fat: 8, carbs: 14 },
    { day: 1, meal_type: "snack", dish: "Творог с мёдом и орехами", kcal: 180, protein: 14, fat: 6, carbs: 18 },
    { day: 1, meal_type: "snack", dish: "Протеиновый батончик", kcal: 190, protein: 20, fat: 6, carbs: 16 },
    { day: 1, meal_type: "snack", dish: "Фруктовый салат", kcal: 120, protein: 2, fat: 1, carbs: 28 },
  ],
  dinner: [
    { day: 1, meal_type: "dinner", dish: "Лосось на пару с овощами", kcal: 390, protein: 36, fat: 16, carbs: 18 },
    { day: 1, meal_type: "dinner", dish: "Том Ям с креветками", kcal: 340, protein: 28, fat: 12, carbs: 26 },
    { day: 1, meal_type: "dinner", dish: "Индейка с запечёнными овощами", kcal: 370, protein: 34, fat: 10, carbs: 28 },
    { day: 1, meal_type: "dinner", dish: "Стейк из говядины с салатом", kcal: 450, protein: 40, fat: 24, carbs: 12 },
    { day: 1, meal_type: "dinner", dish: "Куриный суп-лапша", kcal: 280, protein: 22, fat: 6, carbs: 30 },
  ],
};

// ─── Order History ──────────────────────────────────────────────────────────

export const MOCK_ORDER_HISTORY: OrderHistoryItem[] = [
  {
    ration_id: "r-001",
    date: "2026-03-21",
    total_kcal: 1820,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Овсяная каша с ягодами", kcal: 320 },
      { meal_type: "lunch", name: "Куриная грудка с гречкой", kcal: 480 },
      { meal_type: "snack", name: "Греческий йогурт", kcal: 130 },
      { meal_type: "dinner", name: "Лосось на пару с овощами", kcal: 390 },
    ],
    store_name: "Пятёрочка",
    total_price_rub: 1240,
  },
  {
    ration_id: "r-002",
    date: "2026-03-20",
    total_kcal: 1650,
    status: "generated",
    meals: [
      { meal_type: "breakfast", name: "Творожная запеканка", kcal: 280 },
      { meal_type: "lunch", name: "Борщ с говядиной", kcal: 420 },
      { meal_type: "dinner", name: "Салат Цезарь с курицей", kcal: 350 },
    ],
  },
  {
    ration_id: "r-003",
    date: "2026-03-18",
    total_kcal: 1920,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Яичница с авокадо", kcal: 340 },
      { meal_type: "lunch", name: "Паста с индейкой", kcal: 520 },
      { meal_type: "snack", name: "Протеиновый батончик", kcal: 180 },
      { meal_type: "dinner", name: "Тунец с овощами гриль", kcal: 380 },
    ],
    store_name: "ВкусВилл",
    total_price_rub: 1680,
  },
  {
    ration_id: "r-004",
    date: "2026-03-17",
    total_kcal: 1780,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Сырники со сметаной", kcal: 310 },
      { meal_type: "lunch", name: "Гречка с тефтелями", kcal: 490 },
      { meal_type: "snack", name: "Яблоко и миндаль", kcal: 150 },
      { meal_type: "dinner", name: "Куриный суп-лапша", kcal: 280 },
    ],
    store_name: "Перекрёсток",
    total_price_rub: 1410,
  },
  {
    ration_id: "r-005",
    date: "2026-03-16",
    total_kcal: 1560,
    status: "generated",
    meals: [
      { meal_type: "breakfast", name: "Мюсли с молоком", kcal: 290 },
      { meal_type: "lunch", name: "Плов с курицей", kcal: 450 },
      { meal_type: "dinner", name: "Рыбные котлеты с рисом", kcal: 370 },
    ],
  },
  {
    ration_id: "r-006",
    date: "2026-03-15",
    total_kcal: 1890,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Блины с творогом", kcal: 350 },
      { meal_type: "lunch", name: "Стейк с картофелем", kcal: 580 },
      { meal_type: "snack", name: "Кефир с ягодами", kcal: 120 },
      { meal_type: "dinner", name: "Греческий салат с фетой", kcal: 280 },
    ],
    store_name: "Магнит",
    total_price_rub: 1180,
  },
  {
    ration_id: "r-007",
    date: "2026-03-14",
    total_kcal: 1720,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Каша пшённая с тыквой", kcal: 260 },
      { meal_type: "lunch", name: "Шаурма домашняя с курицей", kcal: 520 },
      { meal_type: "dinner", name: "Запечённая рыба с брокколи", kcal: 340 },
    ],
    store_name: "Пятёрочка",
    total_price_rub: 1150,
  },
  {
    ration_id: "r-008",
    date: "2026-03-13",
    total_kcal: 1680,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Омлет с овощами", kcal: 290 },
      { meal_type: "lunch", name: "Куриные наггетсы с рисом", kcal: 460 },
      { meal_type: "snack", name: "Творог с мёдом", kcal: 170 },
      { meal_type: "dinner", name: "Овощное рагу с говядиной", kcal: 360 },
    ],
    store_name: "ВкусВилл",
    total_price_rub: 1520,
  },
  {
    ration_id: "r-009",
    date: "2026-03-12",
    total_kcal: 1750,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Гранола с йогуртом", kcal: 310 },
      { meal_type: "lunch", name: "Лагман", kcal: 480 },
      { meal_type: "dinner", name: "Филе индейки с овощами", kcal: 390 },
    ],
    store_name: "Перекрёсток",
    total_price_rub: 1380,
  },
  {
    ration_id: "r-010",
    date: "2026-03-11",
    total_kcal: 1620,
    status: "generated",
    meals: [
      { meal_type: "breakfast", name: "Тосты с авокадо", kcal: 280 },
      { meal_type: "lunch", name: "Щи со сметаной", kcal: 350 },
      { meal_type: "dinner", name: "Котлеты из индейки", kcal: 410 },
    ],
  },
  {
    ration_id: "r-011",
    date: "2026-03-10",
    total_kcal: 1840,
    status: "ordered",
    meals: [
      { meal_type: "breakfast", name: "Блинчики с ягодами", kcal: 300 },
      { meal_type: "lunch", name: "Пельмени домашние", kcal: 530 },
      { meal_type: "snack", name: "Банан и орехи", kcal: 200 },
      { meal_type: "dinner", name: "Сёмга на гриле", kcal: 410 },
    ],
    store_name: "Пятёрочка",
    total_price_rub: 1290,
  },
];

// ─── Cart mock ──────────────────────────────────────────────────────────────

export const MOCK_CART: CartData = {
  cart_id: "cart-001",
  total_price_rub: 1240,
  found_count: 6,
  total_count: 7,
  checkout_url: "https://kuper.ru/cart/mock-123",
  items: [
    { ingredient_name: "Куриная грудка", product_name: "Куриная грудка Петелинка 500г", price_rub: 219, found: true, quantity: 1 },
    { ingredient_name: "Греческий йогурт", product_name: "Йогурт Danone Греческий 200г", price_rub: 89, found: true, quantity: 2 },
    { ingredient_name: "Овсяные хлопья", product_name: "Овсянка Геркулес 400г", price_rub: 69, found: true, quantity: 1 },
    { ingredient_name: "Творог 5%", product_name: "Творог Простоквашино 5% 200г", price_rub: 79, found: true, quantity: 1 },
    { ingredient_name: "Лосось", product_name: "Лосось с/с филе 300г", price_rub: 389, found: true, quantity: 1 },
    { ingredient_name: "Брокколи", product_name: "Брокколи замороженная 400г", price_rub: 99, found: true, quantity: 1 },
    { ingredient_name: "Петрушка", product_name: null, price_rub: 0, found: false, quantity: 1 },
  ],
};
