ALTER TABLE ration_meals
    ADD COLUMN IF NOT EXISTS protein_g INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fat_g     INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS carbs_g   INT NOT NULL DEFAULT 0;
